from __future__ import annotations

from datetime import datetime, timedelta
from typing import Literal

import structlog
from pydantic import BaseModel
from supabase._async.client import AsyncClient

from jordan_claw.db.proactive import get_latest_proactive_message
from jordan_claw.tools.calendar import (
    CENTRAL_TZ,
    CalendarAccessError,
    CalendarEvent,
    list_calendar_events,
)

log = structlog.get_logger()


class DailyDigest(BaseModel):
    """The morning briefing already generated by the proactive scheduler."""

    id: str
    content: str
    generated_at: datetime


class TodayResponse(BaseModel):
    """Daily briefing plus a structured upcoming calendar agenda."""

    date: str
    timezone: str
    digest: DailyDigest | None
    calendar_status: Literal["ok", "unavailable"]
    calendar_message: str | None = None
    events: list[CalendarEvent]


async def load_today(
    db: AsyncClient,
    *,
    org_id: str,
    fastmail_username: str,
    fastmail_app_password: str,
    days: int,
    now: datetime | None = None,
) -> TodayResponse:
    """Load server-truth Today data without triggering any agent runs."""
    current = now.astimezone(CENTRAL_TZ) if now is not None else datetime.now(CENTRAL_TZ)
    day_start = current.replace(hour=0, minute=0, second=0, microsecond=0)
    next_day = day_start + timedelta(days=1)
    range_end = day_start + timedelta(days=days)

    row = await get_latest_proactive_message(
        db,
        org_id=org_id,
        task_type="morning_briefing",
        delivered_from=day_start,
        delivered_before=next_day,
    )
    digest = (
        DailyDigest(
            id=row["id"],
            content=row["content"],
            generated_at=row["delivered_at"],
        )
        if row
        else None
    )

    try:
        events = await list_calendar_events(
            fastmail_username,
            fastmail_app_password,
            day_start,
            range_end,
        )
        calendar_status: Literal["ok", "unavailable"] = "ok"
        calendar_message = None
    except CalendarAccessError:
        log.warning("app_today.calendar_unavailable", org_id=org_id)
        events = []
        calendar_status = "unavailable"
        calendar_message = "Calendar is temporarily unavailable."

    return TodayResponse(
        date=day_start.date().isoformat(),
        timezone=str(CENTRAL_TZ),
        digest=digest,
        calendar_status=calendar_status,
        calendar_message=calendar_message,
        events=events,
    )
