import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../shared/api/gateway_config.dart';
import '../shared/api/message_stream_event.dart';
import '../shared/api/mock_data.dart';
import '../shared/models/agent.dart';
import '../shared/models/message.dart';
import 'conversation_state.dart';
import 'core_providers.dart';

// Generated by riverpod_generator (`dart run build_runner build`).
part 'app_state.g.dart';

/// Auth state — true once the user has tapped through passkey or magic link.
///
/// keepAlive: the router only ever `ref.read`s this, so the default
/// autoDispose would drop the signed-in state the moment it was set.
///
/// Live builds boot signed in: the compile-time CLAW_APP_TOKEN is the
/// interim auth (PR2 plan), so there is nothing for a sign-in screen to do.
@Riverpod(keepAlive: true)
class AuthController extends _$AuthController {
  @override
  bool build() => GatewayConfig.isLive;

  void signIn() => state = true;

  void signOut() => state = false;
}

/// Currently selected agent in the chat surface. The dashboard dock and
/// the in-chat agent picker both drive this.
///
/// keepAlive: session state — must survive navigation between tabs.
@Riverpod(keepAlive: true)
class ActiveAgent extends _$ActiveAgent {
  @override
  Agent build() => Agent.roster.first;

  void select(String agentId) => state = Agent.byId(agentId);
}

/// True while an agent is "responding". Drives its typing indicator.
///
/// keepAlive: paired with [AgentThread]'s pending reply timer.
@Riverpod(keepAlive: true)
class AgentTyping extends _$AgentTyping {
  @override
  bool build(String agentId) => false;

  void set(bool value) => state = value;
}

@immutable
class AgentStreamProgressState {
  const AgentStreamProgressState({
    this.status = '',
    this.partialReply = '',
  });

  final String status;
  final String partialReply;
}

/// Ephemeral, safe-to-display activity for one live agent response.
///
/// This never enters conversation history. The gateway only sends
/// argument-free tool labels and final answer text; private model thinking is
/// not part of the stream contract.
@Riverpod(keepAlive: true)
class AgentStreamProgress extends _$AgentStreamProgress {
  @override
  AgentStreamProgressState build(String agentId) {
    return const AgentStreamProgressState();
  }

  void begin() {
    state = const AgentStreamProgressState(status: 'Working');
  }

  void updateStatus(String value) {
    state = AgentStreamProgressState(
      status: value,
      partialReply: state.partialReply,
    );
  }

  void appendText(String value) {
    state = AgentStreamProgressState(
      status: 'Writing response',
      partialReply: '${state.partialReply}$value',
    );
  }

  void clear() {
    state = const AgentStreamProgressState();
  }
}

/// Chat thread per agent. Threads live for the whole session so switching
/// agents (or tabs) never wipes a conversation.
@Riverpod(keepAlive: true)
class AgentThread extends _$AgentThread {
  Timer? _replyTimer;

  @override
  Future<List<Message>> build(String agentId) async {
    ref.onDispose(() => _replyTimer?.cancel());
    if (!GatewayConfig.isLive) return MockData.threadFor(agentId);
    final detail = await ref.read(conversationRepositoryProvider).currentConversation(agentId);
    return detail?.messages ?? const [];
  }

  void appendUserMessage(String body) {
    final current = state.asData;
    if (current == null) return;
    final messages = current.value;
    final message = Message(
      id: 'msg-${DateTime.now().microsecondsSinceEpoch}',
      role: MessageRole.user,
      body: body,
      timestamp: DateTime.now(),
    );
    state = AsyncData([...messages, message]);
    ref.read(agentTypingProvider(agentId).notifier).set(true);
    ref.read(agentStreamProgressProvider(agentId).notifier).begin();

    if (GatewayConfig.isLive) {
      unawaited(_sendToGateway(body));
      return;
    }

    // Mock build: simulate a short think + canned ack so the conversation
    // loop feels real. Rapid sends collapse into one reply — cancel any
    // pending timer so the typing indicator cannot drop early.
    _replyTimer?.cancel();
    _replyTimer = Timer(const Duration(milliseconds: 1400), () {
      if (!ref.mounted) return;
      ref.read(agentTypingProvider(agentId).notifier).set(false);
      ref.read(agentStreamProgressProvider(agentId).notifier).clear();
      state = AsyncData([
        ...(state.asData?.value ?? const <Message>[]),
        Message(
          id: 'msg-${DateTime.now().microsecondsSinceEpoch}',
          role: MessageRole.assistant,
          body: 'Got it. (Mock reply — live builds stream from the gateway.)',
          timestamp: DateTime.now(),
        ),
      ]);
    });
  }

  /// Apply the already-completed voice exchange to the classified agent's
  /// thread. Voice preview sends only after review, so both messages arrive
  /// together rather than showing a typing state on the recording screen.
  void appendVoiceExchange({
    required String transcript,
    required String reply,
  }) {
    final current = state.asData?.value ?? const <Message>[];
    final now = DateTime.now();
    state = AsyncData([
      ...current,
      Message(
        id: 'msg-${now.microsecondsSinceEpoch}-voice-user',
        role: MessageRole.user,
        body: transcript,
        timestamp: now,
      ),
      Message(
        id: 'msg-${now.microsecondsSinceEpoch}-voice-assistant',
        role: MessageRole.assistant,
        body: reply,
        timestamp: now.add(const Duration(milliseconds: 1)),
      ),
    ]);
    ref.read(agentTypingProvider(agentId).notifier).set(false);
    ref.read(agentStreamProgressProvider(agentId).notifier).clear();
    ref.invalidate(conversationHistoryProvider);
  }

  Future<bool> startNewChat() async {
    if (ref.read(agentTypingProvider(agentId))) return false;
    final previous = state.asData?.value ?? const <Message>[];
    state = const AsyncLoading();
    try {
      if (GatewayConfig.isLive) {
        await ref.read(conversationRepositoryProvider).startNewConversation(agentId);
      }
      state = const AsyncData([]);
      ref.invalidate(conversationHistoryProvider);
      return true;
    } on Exception {
      state = AsyncData(previous);
      return false;
    }
  }

  /// Stream safe progress and the final answer from POST /app/messages/stream.
  ///
  /// The agent id IS the gateway slug. Completion replaces any partial text
  /// with the authoritative persisted reply.
  Future<void> _sendToGateway(String body) async {
    String? replyBody;
    try {
      await for (final event
          in ref.read(apiClientProvider).sendMessageStream(agentSlug: agentId, text: body)) {
        if (!ref.mounted) return;
        switch (event.type) {
          case MessageStreamEventType.status:
            ref
                .read(agentStreamProgressProvider(agentId).notifier)
                .updateStatus(event.message ?? 'Working');
          case MessageStreamEventType.delta:
            ref.read(agentStreamProgressProvider(agentId).notifier).appendText(event.text ?? '');
          case MessageStreamEventType.complete:
            replyBody = event.reply ?? '';
          case MessageStreamEventType.error:
            replyBody =
                event.message ?? 'Couldn’t reach the gateway. Check your connection and try again.';
        }
      }
    } on Exception {
      replyBody = 'Couldn’t reach the gateway. Check your connection and try again.';
    }
    if (!ref.mounted) return;
    ref.read(agentTypingProvider(agentId).notifier).set(false);
    ref.read(agentStreamProgressProvider(agentId).notifier).clear();
    state = AsyncData([
      ...(state.asData?.value ?? const <Message>[]),
      Message(
        id: 'msg-${DateTime.now().microsecondsSinceEpoch}',
        role: MessageRole.assistant,
        body: replyBody ?? 'Couldn’t reach the gateway. Check your connection and try again.',
        timestamp: DateTime.now(),
      ),
    ]);
    ref.invalidate(conversationHistoryProvider);
  }
}
