import 'dart:async';

import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../features/room/models/conversation.dart';
import '../features/today/models/today_card_model.dart';
import '../shared/api/mock_data.dart';
import '../shared/models/message.dart';
import '../shared/models/room.dart';
import '../shared/models/skill_info.dart';

// Generated by riverpod_generator. Will be created by `dart run build_runner build`
// on the Mac. The file does not exist on Linux.
part 'app_state.g.dart';

/// Auth state — true once the user has tapped through passkey or magic link.
///
/// keepAlive: the router only ever `ref.read`s this, so the default
/// autoDispose would drop the signed-in state the moment it was set.
@Riverpod(keepAlive: true)
class AuthController extends _$AuthController {
  @override
  bool build() => false;

  void signIn() => state = true;

  void signOut() => state = false;
}

/// Rooms — list of all rooms visible in the drawer. Hardcoded for v1.
@riverpod
List<Room> rooms(Ref ref) => MockData.rooms;

/// Currently active room. Defaults to Claw Main.
///
/// keepAlive: session state — must survive navigation between surfaces.
@Riverpod(keepAlive: true)
class ActiveRoom extends _$ActiveRoom {
  @override
  Room build() => MockData.activeRoom;

  void setActive(String roomId) {
    final next = MockData.roomById(roomId);
    if (next != null && next.isActive) {
      state = next;
    }
  }
}

/// Today cards. Replace with `/api/today/cards` in PR2.
@riverpod
List<TodayCard> todayCards(Ref ref) => MockData.todayCards;

/// True while the assistant is "responding". Drives the typing indicator.
///
/// keepAlive: paired with [ActiveConversation]'s pending reply timer.
@Riverpod(keepAlive: true)
class AssistantTyping extends _$AssistantTyping {
  @override
  bool build() => false;

  void set(bool value) => state = value;
}

/// Active conversation messages for the current room.
///
/// keepAlive: switching to the Context or History tab unmounts the chat
/// tab; autoDispose would wipe the conversation (and drop any pending
/// mock reply) on every tab switch.
@Riverpod(keepAlive: true)
class ActiveConversation extends _$ActiveConversation {
  Timer? _replyTimer;

  @override
  List<Message> build() {
    ref.onDispose(() => _replyTimer?.cancel());
    return MockData.activeMessages;
  }

  void appendUserMessage(String body) {
    final message = Message(
      id: 'msg-${DateTime.now().microsecondsSinceEpoch}',
      role: MessageRole.user,
      body: body,
      timestamp: DateTime.now(),
    );
    state = [...state, message];

    // TODO(backend): post message to gateway and stream the assistant
    // response. Until then, simulate a short think + canned ack so the
    // conversation loop feels real in the mock build.
    ref.read(assistantTypingProvider.notifier).set(true);
    // Rapid sends collapse into one reply — cancel any pending timer so
    // the typing indicator cannot drop early.
    _replyTimer?.cancel();
    _replyTimer = Timer(const Duration(milliseconds: 1400), () {
      if (!ref.mounted) return;
      ref.read(assistantTypingProvider.notifier).set(false);
      state = [
        ...state,
        Message(
          id: 'msg-${DateTime.now().microsecondsSinceEpoch}',
          role: MessageRole.assistant,
          body: 'Got it. (Mock reply — live responses stream in from the '
              'gateway in PR2.)',
          timestamp: DateTime.now(),
        ),
      ];
    });
  }
}

/// Skills loaded into the active room. Read-only in v1.
@riverpod
List<SkillInfo> roomSkills(Ref ref) => MockData.clawMainSkills;

/// History — past conversations for the active room, grouped date-wise in the UI.
@riverpod
List<Conversation> roomHistory(Ref ref) => MockData.history;
