import 'dart:async';

import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../shared/api/api_client.dart';
import '../shared/api/gateway_config.dart';
import '../shared/api/mock_data.dart';
import '../shared/models/agent.dart';
import '../shared/models/message.dart';

// Generated by riverpod_generator (`dart run build_runner build`).
part 'app_state.g.dart';

/// Shared gateway client — one connection pool for the whole session.
@Riverpod(keepAlive: true)
ApiClient apiClient(Ref ref) {
  final client = ApiClient();
  ref.onDispose(client.dispose);
  return client;
}

/// Auth state — true once the user has tapped through passkey or magic link.
///
/// keepAlive: the router only ever `ref.read`s this, so the default
/// autoDispose would drop the signed-in state the moment it was set.
///
/// Live builds boot signed in: the compile-time CLAW_APP_TOKEN is the
/// interim auth (PR2 plan), so there is nothing for a sign-in screen to do.
@Riverpod(keepAlive: true)
class AuthController extends _$AuthController {
  @override
  bool build() => GatewayConfig.isLive;

  void signIn() => state = true;

  void signOut() => state = false;
}

/// Currently selected agent in the chat surface. The dashboard dock and
/// the in-chat agent picker both drive this.
///
/// keepAlive: session state — must survive navigation between tabs.
@Riverpod(keepAlive: true)
class ActiveAgent extends _$ActiveAgent {
  @override
  Agent build() => Agent.roster.first;

  void select(String agentId) => state = Agent.byId(agentId);
}

/// True while an agent is "responding". Drives its typing indicator.
///
/// keepAlive: paired with [AgentThread]'s pending reply timer.
@Riverpod(keepAlive: true)
class AgentTyping extends _$AgentTyping {
  @override
  bool build(String agentId) => false;

  void set(bool value) => state = value;
}

/// Chat thread per agent. Threads live for the whole session so switching
/// agents (or tabs) never wipes a conversation.
@Riverpod(keepAlive: true)
class AgentThread extends _$AgentThread {
  Timer? _replyTimer;

  @override
  List<Message> build(String agentId) {
    ref.onDispose(() => _replyTimer?.cancel());
    // Live threads start empty — the gateway keeps the real conversation
    // history server-side. Seeded threads only make sense in the design build.
    return GatewayConfig.isLive ? const [] : MockData.threadFor(agentId);
  }

  void appendUserMessage(String body) {
    final message = Message(
      id: 'msg-${DateTime.now().microsecondsSinceEpoch}',
      role: MessageRole.user,
      body: body,
      timestamp: DateTime.now(),
    );
    state = [...state, message];
    ref.read(agentTypingProvider(agentId).notifier).set(true);

    if (GatewayConfig.isLive) {
      unawaited(_sendToGateway(body));
      return;
    }

    // Mock build: simulate a short think + canned ack so the conversation
    // loop feels real. Rapid sends collapse into one reply — cancel any
    // pending timer so the typing indicator cannot drop early.
    _replyTimer?.cancel();
    _replyTimer = Timer(const Duration(milliseconds: 1400), () {
      if (!ref.mounted) return;
      ref.read(agentTypingProvider(agentId).notifier).set(false);
      state = [
        ...state,
        Message(
          id: 'msg-${DateTime.now().microsecondsSinceEpoch}',
          role: MessageRole.assistant,
          body: 'Got it. (Mock reply — live responses stream in from the '
              'gateway in PR2.)',
          timestamp: DateTime.now(),
        ),
      ];
    });
  }

  /// Blocking request/reply against POST /app/messages. The agent id IS the
  /// gateway slug; the typing indicator covers the 30-60s agent run.
  Future<void> _sendToGateway(String body) async {
    String replyBody;
    try {
      final reply = await ref
          .read(apiClientProvider)
          .sendMessage(agentSlug: agentId, text: body);
      replyBody = reply.reply;
    } on Exception {
      replyBody =
          'Couldn’t reach the gateway. Check your connection and try again.';
    }
    if (!ref.mounted) return;
    ref.read(agentTypingProvider(agentId).notifier).set(false);
    state = [
      ...state,
      Message(
        id: 'msg-${DateTime.now().microsecondsSinceEpoch}',
        role: MessageRole.assistant,
        body: replyBody,
        timestamp: DateTime.now(),
      ),
    ];
  }
}
